services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongodb_data:/data/db  # Usa volumen nombrado para mejor gestión
    networks:
      - cachozaMongoDB
    restart: always

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS}
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true  # Clave crítica
    ports:
      - "8081:8081"
    networks:
      - cachozaMongoDB
    depends_on:
      - mongo
    restart: always

networks:
  cachozaMongoDB:

volumes:
  mongodb_data:  # Volumen persistente nombrado